apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
    kustomize.toolkit.fluxcd.io/ssa: "Ignore"
data:
  name: ueransim
  namespace: ueransim
