apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-argocd
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: argo-cd-core
    repo: fiach-test-pkgs
    revision: v2
  downstream:
    package: example-argocd
    repo: mgmt-staging
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
