apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ausf/ausf-deployment.yaml
- nrf/nrf-deployment.yaml
- nssf/nssf-deployment.yaml
- pcf/pcf-deployment.yaml
- udm/udm-deployment.yaml
- udr/udr-deployment.yaml
- webui/webui-deployment.yaml
- mongodb/dep-sts.yaml
- ausf/ausf-configmap.yaml
- nrf/nrf-configmap.yaml
- nssf/nssf-configmap.yaml
- pcf/pcf-configmap.yaml
- udm/udm-configmap.yaml
- udr/udr-configmap.yaml
- webui/webui-configmap.yaml
- namespace.yaml
- ausf/ausf-service.yaml
- nrf/nrf-service.yaml
- nssf/nssf-service.yaml
- pcf/pcf-service.yaml
- udm/udm-service.yaml
- udr/udr-service.yaml
- webui/webui-service.yaml
- mongodb/svc.yaml
- mongodb/serviceaccount.yaml
