apiVersion: v2
dependencies:
- condition: mariadb-galera.enabled
  name: mariadb-galera
  repository: file://components/mariadb-galera
  version: ~11.x-0
- condition: policy-clamp-ac-k8s-ppnt.enabled
  name: policy-clamp-ac-k8s-ppnt
  repository: file://components/policy-clamp-ac-k8s-ppnt
  version: ~11.x-0
- condition: policy-clamp-runtime-acm.enabled
  name: policy-clamp-runtime-acm
  repository: file://components/policy-clamp-runtime-acm
  version: ~11.x-0
- condition: policy-models-simulator.enabled
  name: policy-models-simulator
  repository: file://components/policy-models-simulator
  version: ~11.x-0
- condition: policy-api.enabled
  name: policy-api
  repository: file://components/policy-api
  version: ~11.x-0
- condition: policy-pap.enabled
  name: policy-pap
  repository: file://components/policy-pap
  version: ~11.x-0
- condition: policy-apex-pdp.enabled
  name: policy-apex-pdp
  repository: file://components/policy-apex-pdp
  version: ~11.x-0
- condition: policy-clamp-ac-pf-ppnt.enabled
  name: policy-clamp-ac-pf-ppnt
  repository: file://components/policy-clamp-ac-pf-ppnt
  version: ~11.x-0
- condition: policy-drools-pdp.enabled
  name: policy-drools-pdp
  repository: file://components/policy-drools-pdp
  version: ~11.x-0
- condition: policy-xacml-pdp.enabled
  name: policy-xacml-pdp
  repository: file://components/policy-xacml-pdp
  version: ~11.x-0
- condition: policy-distribution.enabled
  name: policy-distribution
  repository: file://components/policy-distribution
  version: ~11.x-0
- condition: policy-clamp-ac-http-ppnt.enabled
  name: policy-clamp-ac-http-ppnt
  repository: file://components/policy-clamp-ac-http-ppnt
  version: ~11.x-0
- condition: policy-clamp-ac-kserve-ppnt.enabled
  name: policy-clamp-ac-kserve-ppnt
  repository: file://components/policy-clamp-ac-kserve-ppnt
  version: ~11.x-0
- condition: policy-clamp-ac-a1pms-ppnt.enabled
  name: policy-clamp-ac-a1pms-ppnt
  repository: file://components/policy-clamp-ac-a1pms-ppnt
  version: ~11.x-0
description: ONAP Policy
name: policy
version: 11.0.0
