apiVersion: req.nephio.org/v1alpha1
kind: Capacity
metadata:
  name: control-plane
  annotations:
    config.kubernetes.io/local-config: "true"
    kustomize.toolkit.fluxcd.io/ssa: "Ignore"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.amf-example
    specializer.nephio.org/namespace: example
spec:
  maxSubscribers: 10000
