apiVersion: v1
kind: Secret
metadata:
  name: git-user-secret
  namespace: gitea
  labels:
    app: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
type: kubernetes.io/basic-auth
stringData:
  username: nephio
  password: secret