apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: acm
  name: policy
rules:
- apiGroups:
  - ""
  - apps
  - batch
  resources:
  - pods
  - statefulsets
  - jobs/status
  verbs:
  - get
  - watch
  - list
