apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-gitrepo # kpt-set: ${gitrepoName}
  namespace: example-ns
spec:
  interval: 1m
  url: https://github.com/efiacor/test
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts dir
    !/charts
