apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/hello-world
      version: '0.1.x'
      sourceRef:
        kind: GitRepository
        name: hello-test
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    fullnameOverride: super-hello
